### ISSUE TITLE
Calling Vesting contract calculateGrantClaim for grant with future startTime causes exception

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyToken#7]
When calling `calculateGrantClaim` on the Vesting contract for a grant with a `startTime` in the future causes a VM exception rather than the expected behaviour of returning `(0, 0)`.

As discussed with @area this may only be an issue with `ganache-cli` clients, but I've not yet tested with other clients. Might also be the case that this isn't worth fixing, but an explicit check for a future `startTime` would solve it.

This isn't really high priority, I've worked around it by introducing a try/catch around the JS call to it. Just bringing to your attention 😄

**Comment by elenadimitrova** [comment]
After some consideration arguments (below) weighted in on leaving the contract as-is
- Testing with `geth` returns back `(0, 0)`
- For creating grants that can't be claimed for some time we'll be using the respective `vestingCliff` value rather than a future start date. It would have been better to actually check the `startDate` provided is in the past but atm that alone does not warrant a mainnet redeploy

**Comment by elenadimitrova** [comment]
We'll have to redeploy the Vesting contract so we might as well deal with this change there.
